# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160817_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='post',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
