# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0003_auto_20160817_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='item_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_obj', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='feed',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
