# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160818_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='item_ct',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='item_id',
        ),
    ]
