# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 03:49
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('posts', '0005_auto_20160819_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='hashtags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
