# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_feed_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='hashtags',
            new_name='tags',
        ),
    ]
