# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_activity_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='action',
            old_name='created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='action',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.Action'),
        ),
    ]
