# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20160819_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='verb',
        ),
    ]
