# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_remove_action_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='verb',
            field=models.CharField(default=datetime.datetime(2016, 8, 19, 16, 4, 23, 830015), max_length=255),
            preserve_default=False,
        ),
    ]
