# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_auto_20161006_1856'),
        ('actions', '0005_action_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Followed'), ('A', 'Answered'), ('W', 'Accepted Answer'), ('E', 'Edited Article'), ('S', 'Also Commented'), ('I', 'Image Liked'), ('N', 'Image Commented')], max_length=1),
        ),
    ]
