# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20160704_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='users_like',
        ),
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
