# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20160831_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
