# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_image_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/%Y/%m/%d'),
        ),
    ]
