# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20160914_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=images.models.upload_to),
        ),
    ]
