# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='created',
            new_name='date',
        ),
    ]
